spring:
  rabbitmq:
    host: 172.3.12.6
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://172.3.12.6:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver